rootProject.name = 'zhihuidangjian'

include 'server'
include 'services'
include 'services:ai'
include 'services:auth'
include 'services:common'
include 'services:common:common-core'
include 'services:common:common-web'
include 'services:common:common-data-mybatis'
include 'services:common:common-redis'
include 'services:common:common-security'
include 'services:content'
include 'services:article'
include 'services:category'
include 'services:chapter'
include 'services:course'
include 'services:graph'
include 'services:learning'
include 'services:quiz'
include 'services:search'
include 'services:user'
include 'services:resource'
include 'services:social'
