sonar.projectKey=zhihui-dangjian
sonar.projectName=ZhihuiDangjian
sonar.organization=agg233
sonar.sources=.
sonar.java.binaries=**/build/classes
sonar.java.source=21
sonar.coverage.jacoco.xmlReportPaths=server/build/reports/jacoco/test/jacocoTestReport.xml
sonar.exclusions=**/build/**
sonar.coverage.exclusions=**/test/**