app:
  security:
    enabled: false
  dev:
    default-user-id: 1987026098687483905
server:
  port: 9000
  ai:
    openai:
      api-key: ${AI_KEY:dummy-key}

logging:
  level:
    root: INFO
    com.rauio.smartdangjian: DEBUG