app:
  security:
    enabled: false
  dev:
    default-user-id: 1987026098687483905
server:
  port: 9000
  ai:
    openai:
      api-key: ${AI_KEY:dummy-key}

dromara:
  x-file-storage:
    tencent-cos:
      - platform: tencent-cos
        enable-storage: false
    local:
      - platform: local-dev
        enable-storage: true
        storage-path: ./uploads
        domain: http://localhost:9000/

logging:
  level:
    root: INFO
    com.rauio.smartdangjian: DEBUG