CREATE TABLE IF NOT EXISTS ai_skill (
    id VARCHAR(64) PRIMARY KEY,
    agent_type VARCHAR(32) NOT NULL,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    content TEXT NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    sort INT NOT NULL DEFAULT 0,
    tool_groups JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ai_skill_name (name)
);

ALTER TABLE ai_prompts
    ADD COLUMN IF NOT EXISTS agent_type VARCHAR(32) NOT NULL DEFAULT 'COMMON' AFTER id,
    ADD COLUMN IF NOT EXISTS enabled TINYINT(1) NOT NULL DEFAULT 1 AFTER role,
    ADD COLUMN IF NOT EXISTS sort INT NOT NULL DEFAULT 0 AFTER enabled;

ALTER TABLE ai_chat_message
    ADD COLUMN IF NOT EXISTS agent_type VARCHAR(32) NULL AFTER user_id;
